import type { Metadata } from "next";
import "./globals.css";
import { AndroidRedirectProvider } from "./(ui)/components/redirect/AndroidRedirectProvider";
import { SmartRedirectWrapper } from './(ui)/components/redirect/SmartRedirectWrapper';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const appConfig = {
  packageName: 'com.mathias8dev.pocengie',
  scheme: 'krakenapp',
  playStoreUrl: 'https://play.google.com/store/apps/details?id=com.mathias8dev.pocengie',
  fallbackDelay: 1500
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <AndroidRedirectProvider config={appConfig}>
          <SmartRedirectWrapper
            showBanner={true}
            autoRedirect={false}
            bannerProps={{
              title: 'PocEngie',
              description: 'Get the full experience in our mobile app'
            }}
          >
            {children}
          </SmartRedirectWrapper></AndroidRedirectProvider>

      </body>
    </html>
  );
}
